/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkTijaratiProRouteImport } from './routes/work/tijarati-pro'
import { Route as WorkSnapgoRouteImport } from './routes/work/snapgo'
import { Route as WorkDetailingLabRouteImport } from './routes/work/detailing-lab'
import { Route as WorkDataInsightsRouteImport } from './routes/work/data-insights'
import { Route as MenusMarleysRouteImport } from './routes/menus/marleys'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTijaratiProRoute = WorkTijaratiProRouteImport.update({
  id: '/work/tijarati-pro',
  path: '/work/tijarati-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSnapgoRoute = WorkSnapgoRouteImport.update({
  id: '/work/snapgo',
  path: '/work/snapgo',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDetailingLabRoute = WorkDetailingLabRouteImport.update({
  id: '/work/detailing-lab',
  path: '/work/detailing-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDataInsightsRoute = WorkDataInsightsRouteImport.update({
  id: '/work/data-insights',
  path: '/work/data-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusMarleysRoute = MenusMarleysRouteImport.update({
  id: '/menus/marleys',
  path: '/menus/marleys',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menus/marleys': typeof MenusMarleysRoute
  '/work/data-insights': typeof WorkDataInsightsRoute
  '/work/detailing-lab': typeof WorkDetailingLabRoute
  '/work/snapgo': typeof WorkSnapgoRoute
  '/work/tijarati-pro': typeof WorkTijaratiProRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menus/marleys'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/snapgo'
    | '/work/tijarati-pro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menus/marleys'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/snapgo'
    | '/work/tijarati-pro'
  id:
    | '__root__'
    | '/'
    | '/menus/marleys'
    | '/work/data-insights'
    | '/work/detailing-lab'
    | '/work/snapgo'
    | '/work/tijarati-pro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenusMarleysRoute: typeof MenusMarleysRoute
  WorkDataInsightsRoute: typeof WorkDataInsightsRoute
  WorkDetailingLabRoute: typeof WorkDetailingLabRoute
  WorkSnapgoRoute: typeof WorkSnapgoRoute
  WorkTijaratiProRoute: typeof WorkTijaratiProRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/tijarati-pro': {
      id: '/work/tijarati-pro'
      path: '/work/tijarati-pro'
      fullPath: '/work/tijarati-pro'
      preLoaderRoute: typeof WorkTijaratiProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/snapgo': {
      id: '/work/snapgo'
      path: '/work/snapgo'
      fullPath: '/work/snapgo'
      preLoaderRoute: typeof WorkSnapgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/detailing-lab': {
      id: '/work/detailing-lab'
      path: '/work/detailing-lab'
      fullPath: '/work/detailing-lab'
      preLoaderRoute: typeof WorkDetailingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/data-insights': {
      id: '/work/data-insights'
      path: '/work/data-insights'
      fullPath: '/work/data-insights'
      preLoaderRoute: typeof WorkDataInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus/marleys': {
      id: '/menus/marleys'
      path: '/menus/marleys'
      fullPath: '/menus/marleys'
      preLoaderRoute: typeof MenusMarleysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenusMarleysRoute: MenusMarleysRoute,
  WorkDataInsightsRoute: WorkDataInsightsRoute,
  WorkDetailingLabRoute: WorkDetailingLabRoute,
  WorkSnapgoRoute: WorkSnapgoRoute,
  WorkTijaratiProRoute: WorkTijaratiProRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
